# Generated by Django 5.1.1 on 2025-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_chead2_blogpost_head2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(default='', upload_to='blogs/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(default='', upload_to='blogs/images'),
        ),
    ]
