# Generated by Django 5.1.1 on 2025-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_author_blogpost_image1_blogpost_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
    ]
