# Generated by Django 5.1.1 on 2025-07-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogpost_image1_alter_blogpost_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='blogs/images')),
                ('first_name', models.CharField(default='not defined', max_length=50)),
                ('last_name', models.CharField(default='not defined', max_length=50)),
                ('mobile_number', models.IntegerField(default='not defined', max_length=10)),
                ('alternate_mobile_number', models.IntegerField(default='not defined', max_length=10)),
                ('email', models.EmailField(default='not defined', max_length=60)),
                ('country', models.CharField(default='not defined', max_length=50)),
                ('state', models.CharField(default='not defined', max_length=50)),
                ('city', models.CharField(default='not defined', max_length=50)),
                ('pincode', models.IntegerField(default='not defined', max_length=10)),
            ],
        ),
    ]
