# Generated by Django 5.1.1 on 2025-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='alternate_mobile_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='mobile_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
