# Generated by Django 5.1.1 on 2025-08-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_category_blogpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
