# Generated by Django 5.1.1 on 2025-08-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_blogpost_likes_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
