# Generated by Django 5.1.1 on 2025-08-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_logininstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
