# Generated by Django 5.1.1 on 2025-08-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_custom_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
