# Generated by Django 5.1.1 on 2025-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_custom_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
